// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import Charts__SpendingBreakdownController from "./charts/spending_breakdown_controller"
application.register("charts--spending-breakdown", Charts__SpendingBreakdownController)

import MoneyFieldController from "./money_field_controller"
application.register("money-field", MoneyFieldController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)
